[workspace]
members = ["game"]

resolver = "2"

# Enable a small amount of optimization in debug mode.
[profile.dev]
opt-level = 1

# Enable high optimizations for dependencies (including Bevy).
[profile.dev.package."*"]
opt-level = 3
